# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "kalilinux/rolling"

  # Install missing plugins
  unless Vagrant.has_plugin?("vagrant-vmware-desktop")
    puts 'Installing vagrant-vmware-desktop Plugin...'
    system('vagrant plugin install vagrant-vmware-desktop')
  end

  config.vm.define "kali-main" do |kali|
    kali.vm.hostname = "kali-main"

    kali.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.vmx["name"] = "kali-main"
      v.vmx["memsize"] = "8192"
      v.vmx["numvcpus"] = "2"
      v.vmx["svga.vramSize"] = "134217728" #VRAM 128MB
      v.vmx["ethernet0.pcislotnumber"] = "160"
    end
  end

  config.vm.synced_folder "resources", "/tmp/resources"
  
  config.vm.provision "shell", path: "config.sh"

  config.vm.provision "shell", path: "provision.sh"

end
