# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "kalilinux/rolling"

  config.vm.define "kali-main" do |kali|
    kali.vm.hostname = "kali-main"

    kali.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.vmx["name"] = "kali-main"
      v.vmx["memsize"] = "8192"
      v.vmx["numvcpus"] = "2"
      v.vmx["svga.vramSize"] = "134217728" #VRAM 128MB
    end
  end

  config.vm.provision "shell", path: "provision.sh", :args => "--keyboard=fr --timezone=Europe/Paris"

end
